# Generated by Django 3.0.5 on 2021-04-13 20:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('inst_id', models.UUIDField()),
                ('cate_name', models.TextField(unique=True)),
                ('cate_description', models.TextField()),
                ('cate_type', models.TextField()),
                ('cate_status', models.TextField()),
            ],
            options={
                'db_table': 'category',
            },
        ),
    ]
