# Generated by Django 3.0.5 on 2021-10-10 20:19

import uuid

import djongo.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUserModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('fous_user_id', models.UUIDField()),
                ('fous_is_bidirectional', models.BooleanField(default=False)),
                ('inst_id_user', models.UUIDField()),
                ('inst_id_fous', models.UUIDField()),
                ('name_user', models.TextField()),
                ('name_fous', models.TextField()),
                ('inst_name_user', models.TextField()),
                ('inst_name_fous', models.TextField()),
                ('user_email', models.TextField()),
                ('fous_email', models.TextField()),
                ('user_degree', djongo.models.fields.JSONField()),
                ('fous_degree', djongo.models.fields.JSONField()),
                ('user_photo', models.UUIDField()),
                ('fous_photo', models.UUIDField()),
            ],
            options={
                'db_table': 'follow_user',
            },
        ),
    ]
