# Generated by Django 3.0.5 on 2021-10-10 20:19

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityUserModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comm_id', models.UUIDField()),
                ('comm_owner_id', models.UUIDField()),
                ('comm_photo', models.UUIDField()),
                ('inst_id', models.UUIDField()),
                ('user_id', models.UUIDField()),
                ('cous_pending_approval', models.BooleanField()),
                ('inst_name', models.TextField()),
                ('cous_admin', models.BooleanField()),
                ('comm_name', models.TextField()),
                ('user_name', models.TextField()),
                ('user_email', models.TextField()),
                ('user_phone', models.TextField()),
                ('user_photo', models.UUIDField()),
                ('comm_category_name', models.TextField()),
            ],
            options={
                'db_table': 'community_user',
            },
        ),
    ]
