# Generated by Django 3.0.5 on 2021-10-10 20:19

import uuid

import djongo.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('inst_id', models.UUIDField()),
                ('inst_name', models.TextField()),
                ('user_name', models.TextField()),
                ('user_email', models.TextField(unique=True)),
                ('user_password', models.TextField()),
                ('user_provider', models.TextField()),
                ('user_role', djongo.models.fields.JSONField()),
                ('user_role_structure', djongo.models.fields.JSONField()),
                ('role_active', models.UUIDField()),
                ('user_admin', models.BooleanField()),
                ('user_intro', models.TextField()),
                ('user_phone', models.TextField()),
                ('user_photo', models.TextField()),
                ('user_gender', models.TextField()),
                ('user_degree', djongo.models.fields.JSONField()),
                ('user_projects', djongo.models.fields.JSONField()),
                ('user_curriculum_vitae', models.UUIDField()),
                ('user_skill', djongo.models.fields.JSONField()),
                ('user_interest', djongo.models.fields.JSONField()),
                ('user_country', djongo.models.fields.JSONField()),
                ('user_department', djongo.models.fields.JSONField()),
                ('user_municipality', djongo.models.fields.JSONField()),
                ('user_status', models.TextField()),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
