# Generated by Django 3.0.5 on 2021-10-10 20:19

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('inst_id', models.UUIDField()),
                ('comm_photo_id', models.UUIDField()),
                ('comm_owner_id', models.UUIDField()),
                ('comm_name', models.TextField()),
                ('comm_description', models.TextField()),
                ('comm_category', models.UUIDField()),
                ('comm_category_name', models.TextField()),
                ('comm_privacy', models.BooleanField(default=False)),
                ('comm_amount_member', models.IntegerField()),
            ],
            options={
                'db_table': 'community',
            },
        ),
    ]
