export const environment = {
  production: true,
  urlChat: 'https://studentsprojects.cloud.ufps.edu.co/asn_balancing/api_gateway/asn_chat/chats/api/',
  chatWebsocket: 'wss://studentsprojects.cloud.ufps.edu.co/asn_balancing_socket/socket_chat/wss/',
  notificationUrl: 'https://studentsprojects.cloud.ufps.edu.co/asn_balancing/api_gateway/asn_notification/notifications/api/',
  notificationWebSocket: 'wss://studentsprojects.cloud.ufps.edu.co/asn_balancing_socket/socket_notification/wss/',
  file: 'https://studentsprojects.cloud.ufps.edu.co/asn_balancing/api_gateway/asn_file/files/api/file/get_object/',
  fileUrl: 'https://studentsprojects.cloud.ufps.edu.co/asn_balancing/api_gateway/asn_file/files/api/',
  institutionUrl: 'https://studentsprojects.cloud.ufps.edu.co/asn_balancing/api_gateway/asn_institution/institutions/api/',
  publicationUrl: 'https://studentsprojects.cloud.ufps.edu.co/asn_balancing/api_gateway/asn_publication/publications/api/',
  securityUrl: 'https://studentsprojects.cloud.ufps.edu.co/asn_balancing/api_gateway/asn_security/securities/api/',
  userUrl: 'https://studentsprojects.cloud.ufps.edu.co/asn_balancing/api_gateway/asn_user/users/api/',
  utilityUrl: 'https://studentsprojects.cloud.ufps.edu.co/asn_balancing/api_gateway/asn_utility/utilities/api/',
  defaultImage: '3fa85f64-5717-4562-b3fc-2c963f66afa6/',
  imgUser: '992f149f-b056-484b-bc0b-573eca93f90f/',
};
