# Generated by Django 3.0.5 on 2021-10-11 15:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('inst_name', models.TextField(unique=True)),
                ('inst_photo', models.UUIDField()),
                ('inst_address', models.TextField()),
                ('inst_country', models.TextField()),
                ('inst_department', models.TextField()),
                ('inst_municipality', models.TextField()),
                ('inst_head', models.TextField()),
                ('inst_website', models.TextField()),
                ('inst_phone', models.TextField()),
                ('inst_fax', models.TextField()),
            ],
            options={
                'db_table': 'institution',
            },
        ),
    ]
