# Generated by Django 3.0.5 on 2022-01-15 15:49

import datetime
from django.db import migrations, models
import djongo.models.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OpportunityModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('inst_id', models.UUIDField()),
                ('user_id', models.UUIDField()),
                ('user_name', models.TextField()),
                ('user_photo', models.UUIDField()),
                ('oppo_title', models.TextField()),
                ('oppo_description', models.TextField()),
                ('oppo_expiration_date', models.DateTimeField()),
                ('oppo_employer_email', models.EmailField(max_length=254)),
                ('oppo_simple_request', models.BooleanField()),
                ('oppo_application_url', models.URLField()),
                ('oppo_type_contract', models.TextField()),
                ('oppo_postulates', djongo.models.fields.JSONField()),
                ('oppo_attachments', djongo.models.fields.JSONField()),
                ('oppo_user_saved', djongo.models.fields.JSONField()),
                ('oppo_country', djongo.models.fields.JSONField()),
                ('oppo_department', djongo.models.fields.JSONField()),
                ('oppo_municipality', djongo.models.fields.JSONField()),
                ('oppo_remuneration', models.TextField()),
                ('created_date', models.DateTimeField(default=datetime.datetime.now, editable=False)),
            ],
            options={
                'db_table': 'opportunity',
            },
        ),
    ]
