# Generated by Django 3.0.5 on 2021-10-10 20:19

import uuid

import djongo.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoleModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('inst_id', models.UUIDField()),
                ('role_name', models.TextField()),
                ('role_list_module', djongo.models.fields.JSONField(default=[{}])),
                ('role_structure', djongo.models.fields.JSONField()),
                ('role_static', models.BooleanField()),
                ('role_status', models.TextField()),
            ],
            options={
                'db_table': 'role',
            },
        ),
    ]
