# Generated by Django 3.0.5 on 2021-06-07 22:02

from django.db import migrations, models
import djongo.models.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('user_name', models.TextField()),
                ('user_photo', models.UUIDField()),
                ('inst_id', models.UUIDField()),
                ('comm_id', models.UUIDField()),
                ('cate_id', models.UUIDField()),
                ('cate_name', models.TextField()),
                ('comm_name', models.TextField()),
                ('publ_title', models.TextField()),
                ('publ_description', models.TextField()),
                ('publ_standard', models.BooleanField()),
                ('publ_authors', djongo.models.fields.JSONField()),
                ('publ_privacy', models.BooleanField()),
                ('publ_date', models.DateTimeField()),
                ('publ_comment', djongo.models.fields.JSONField()),
                ('publ_interested_list', djongo.models.fields.JSONField()),
                ('user_interested', models.BooleanField()),
                ('publ_amount_shared', models.IntegerField()),
                ('publ_amount_download', models.IntegerField()),
                ('publ_attachments', djongo.models.fields.JSONField()),
                ('publ_full_text', models.BooleanField()),
                ('publ_link_doi', models.TextField()),
                ('publ_permission_view_full_text', djongo.models.fields.JSONField()),
                ('created_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'publication',
            },
        ),
    ]
